# Generated by Django 5.1.6 on 2025-02-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='pfp_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
