# Generated by Django 5.1.6 on 2025-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_member_pfp_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
