# Generated by Django 5.1.6 on 2025-06-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_link_event_other_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('bg_img', models.ImageField(blank=True, null=True, upload_to='background_images/')),
            ],
        ),
        migrations.CreateModel(
            name='BgVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='background_videos/')),
                ('video_url', models.URLField(blank=True, help_text='Optional: Use this for externally hosted videos (e.g., from a CDN).', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BgMedia',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='thumbnail_url',
            new_name='thumbnail_img',
        ),
        migrations.RemoveField(
            model_name='event',
            name='poster_link',
        ),
        migrations.RemoveField(
            model_name='member',
            name='pfp_url',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='logo',
        ),
        migrations.AddField(
            model_name='event',
            name='poster_img',
            field=models.ImageField(blank=True, null=True, upload_to='event_posters/'),
        ),
        migrations.AddField(
            model_name='member',
            name='pfp_img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='member_pfps/'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='sponsor_logos/'),
        ),
    ]
