# Generated by Django 5.1.6 on 2025-06-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bgimage_bgvideo_delete_bgmedia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircularGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='circular_gallery/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
