# Generated by Django 5.1.6 on 2025-06-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_circulargalleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_hero/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home_hero/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='resource_carousel/')),
                ('link', models.URLField(blank=True, help_text='Optional: Link the image to a resource or external page.', null=True)),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail_img',
            field=models.ImageField(default='thumbnail', upload_to='resource_thumbnails/'),
            preserve_default=False,
        ),
    ]
