# Generated by Django 5.1.6 on 2025-06-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_eventheroimage_servicesbgimage_servicesheroimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='alumni_hero/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubAlumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('pfp_img', models.ImageField(blank=True, null=True, upload_to='alumni_profiles/')),
            ],
        ),
    ]
