# Generated by Django 5.1.6 on 2025-06-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_joinusbgimage_joinusheroimage_telferalumnus'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='navbar_logo/')),
            ],
        ),
        migrations.DeleteModel(
            name='BgImage',
        ),
        migrations.DeleteModel(
            name='BgVideo',
        ),
    ]
