# Generated by Django 5.1.6 on 2025-06-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_navbarlogo_delete_bgimage_delete_bgvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitBgImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='benefit_bg/')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='resource_hero/')),
                ('caption', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
