# Generated by Django 5.1.6 on 2025-06-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_benefitbgimage_resourceheroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the event', null=True),
        ),
    ]
