# Generated by Django 5.1.6 on 2025-06-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_event_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinUsBgImage',
        ),
        migrations.AlterField(
            model_name='alumniheroimage',
            name='image',
            field=models.ImageField(help_text='Only one Alumni hero image is allowed. Delete the existing one before adding a new one.', upload_to='alumni_hero/'),
        ),
        migrations.AlterField(
            model_name='eventheroimage',
            name='image',
            field=models.ImageField(help_text='Only one Event hero image is allowed. Delete the existing one before adding a new one.', upload_to='event_hero/'),
        ),
        migrations.AlterField(
            model_name='joinusheroimage',
            name='image',
            field=models.ImageField(help_text='Only one Join Us hero image is allowed. Delete the existing one before adding a new one.', upload_to='join_us_hero/'),
        ),
        migrations.AlterField(
            model_name='resourceheroimage',
            name='image',
            field=models.ImageField(help_text='Only one Resource hero image is allowed. Delete the existing one before adding a new one.', upload_to='resource_hero/'),
        ),
        migrations.AlterField(
            model_name='servicesheroimage',
            name='image',
            field=models.ImageField(help_text='Only one Services hero image is allowed. Delete the existing one before adding a new one.', upload_to='services_hero/'),
        ),
    ]
