# Generated by Django 5.1.6 on 2025-06-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_delete_joinusbgimage_alter_alumniheroimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumniheroimage',
            options={'verbose_name': 'Alumni Hero Image', 'verbose_name_plural': 'Alumni Hero Image'},
        ),
        migrations.AlterModelOptions(
            name='benefitbgimage',
            options={'verbose_name': 'Benefit Background Image', 'verbose_name_plural': 'Benefit Background Images'},
        ),
        migrations.AlterModelOptions(
            name='circulargalleryimage',
            options={'verbose_name': 'Circular Gallery Image', 'verbose_name_plural': 'Circular Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='clubalumnus',
            options={'verbose_name': 'Club Alumnus', 'verbose_name_plural': 'Club Alumni'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventheroimage',
            options={'verbose_name': 'Event Hero Image', 'verbose_name_plural': 'Event Hero Image'},
        ),
        migrations.AlterModelOptions(
            name='homeheromedia',
            options={'verbose_name': 'Home Hero Media', 'verbose_name_plural': 'Home Hero Media'},
        ),
        migrations.AlterModelOptions(
            name='joinusheroimage',
            options={'verbose_name': 'Join Us Hero Image', 'verbose_name_plural': 'Join Us Hero Image'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='navbarlogo',
            options={'verbose_name': 'Navbar Logo', 'verbose_name_plural': 'Navbar Logos'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
        migrations.AlterModelOptions(
            name='resourcecarouselimage',
            options={'verbose_name': 'Resource Carousel Image', 'verbose_name_plural': 'Resource Carousel Images'},
        ),
        migrations.AlterModelOptions(
            name='resourceheroimage',
            options={'verbose_name': 'Resource Hero Image', 'verbose_name_plural': 'Resource Hero Image'},
        ),
        migrations.AlterModelOptions(
            name='servicesbgimage',
            options={'verbose_name': 'Services Background Image', 'verbose_name_plural': 'Services Background Images'},
        ),
        migrations.AlterModelOptions(
            name='servicesheroimage',
            options={'verbose_name': 'Services Hero Image', 'verbose_name_plural': 'Services Hero Image'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterModelOptions(
            name='telferalumnus',
            options={'verbose_name': 'Telfer Alumnus', 'verbose_name_plural': 'Telfer Alumni'},
        ),
    ]
