# Generated by Django 5.1.6 on 2025-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_alumniheroimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Position title', max_length=200)),
                ('description', models.TextField(help_text='Reminder to list down important things you want the applicant to include in their resume')),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when the position was posted')),
            ],
            options={
                'verbose_name': 'Open Position',
                'verbose_name_plural': 'Open Positions',
            },
        ),
    ]
