# Generated by Django 5.1.6 on 2025-06-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_openposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openposition',
            name='posted_at',
            field=models.DateField(help_text='Datetime when the position was posted'),
        ),
    ]
