# Generated by Django 5.1.6 on 2025-06-19 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_openposition_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openposition',
            name='description',
            field=models.TextField(help_text='Reminder to list down important things you want the applicant to include in their resume', validators=[django.core.validators.MaxLengthValidator(330)]),
        ),
    ]
