# Generated by Django 5.1.6 on 2025-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='content_url',
        ),
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(default='awd', max_length=500, upload_to='designs/'),
            preserve_default=False,
        ),
    ]
