# Generated by Django 5.1.6 on 2026-09-06 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_design_content_url_design_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('preferred_name', models.CharField(max_length=200)),
                ('uottawa_email', models.EmailField(max_length=254)),
                ('personal_email', models.EmailField(blank=True, max_length=254)),
                ('wechat_id', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.URLField(blank=True)),
                ('program', models.CharField(max_length=200)),
                ('year_of_study', models.CharField(max_length=20)),
                ('expected_graduation_year', models.PositiveIntegerField()),
                ('interested_industries', models.JSONField(blank=True, default=list)),
                ('preferred_event_types', models.JSONField(blank=True, default=list)),
                ('notify_consent', models.BooleanField(default=False)),
                ('terms_agreed', models.BooleanField(default=False)),
                ('privacy_agreed', models.BooleanField(default=False)),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('payment_review', 'Payment Review'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('no_show_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club member',
                'verbose_name_plural': 'Club members',
            },
        ),
        migrations.CreateModel(
            name='MembershipSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(default='TCSA', max_length=200)),
                ('interac_email', models.EmailField(blank=True, max_length=254)),
                ('interac_phone', models.CharField(blank=True, max_length=40)),
                ('instruction_text', models.TextField(blank=True, default='Send an Interac e-transfer for the exact amount. Put your member ID in the memo so VP Finance can match your payment.')),
                ('contact_email', models.EmailField(blank=True, default='membership@tcsaofficial.com', max_length=254)),
            ],
            options={
                'verbose_name': 'Membership settings',
                'verbose_name_plural': 'Membership settings',
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_cad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Membership type',
                'verbose_name_plural': 'Membership types',
                'ordering': ['price_cad'],
            },
        ),
        migrations.CreateModel(
            name='MemberEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField(blank=True)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('member_slots', models.PositiveIntegerField(default=0)),
                ('public_slots', models.PositiveIntegerField(default=0)),
                ('staff_slots', models.PositiveIntegerField(default=0)),
                ('member_registration_opens', models.DateTimeField(blank=True, null=True)),
                ('public_registration_opens', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('waitlist_enabled', models.BooleanField(default=True)),
                ('requires_review', models.BooleanField(default=False)),
                ('requires_deposit', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leads', models.ManyToManyField(blank=True, related_name='led_member_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member event',
                'verbose_name_plural': 'Member events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_ref', models.CharField(max_length=20, unique=True)),
                ('form_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='api.clubmember')),
            ],
            options={
                'verbose_name': 'Membership application',
                'verbose_name_plural': 'Membership applications',
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_expected', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('method', models.CharField(choices=[('etransfer', 'Interac e-transfer')], default='etransfer', max_length=20)),
                ('interac_reference', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('awaiting', 'Awaiting'), ('confirmed', 'Confirmed'), ('mismatch', 'Mismatch'), ('refunded', 'Refunded')], default='awaiting', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('refund_reason', models.TextField(blank=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.membershipapplication')),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.clubmember')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_membership_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membership payment',
                'verbose_name_plural': 'Membership payments',
            },
        ),
        migrations.CreateModel(
            name='MembershipStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_status_changes', to=settings.AUTH_USER_MODEL)),
                ('club_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='api.clubmember')),
            ],
            options={
                'verbose_name': 'Membership status log',
                'verbose_name_plural': 'Membership status logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clubmember',
            name='membership_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='api.membershiptype'),
        ),
        migrations.CreateModel(
            name='MemberEventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('member_id_entered', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No-show')], default='submitted', max_length=20)),
                ('attendance', models.CharField(blank=True, choices=[('', '—'), ('attended', 'Attended'), ('cancelled_on_time', 'Cancelled on time'), ('late_cancel', 'Late cancellation'), ('no_show', 'No-show'), ('excused', 'Excused absence')], default='', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_signups', to='api.clubmember')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='api.memberevent')),
            ],
            options={
                'verbose_name': 'Member event signup',
                'verbose_name_plural': 'Member event signups',
                'constraints': [models.UniqueConstraint(fields=('event', 'email'), name='unique_member_event_email_signup')],
            },
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'payment_review', 'suspended'])), fields=('uottawa_email',), name='unique_blocking_uottawa_email'),
        ),
    ]
